//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8083/dp2mserver")]
        public string config_url {
            get {
                return ((string)(this["config_url"]));
            }
            set {
                this["config_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_userName {
            get {
                return ((string)(this["config_userName"]));
            }
            set {
                this["config_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_password {
            get {
                return ((string)(this["config_password"]));
            }
            set {
                this["config_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getInfo_remoteUserName {
            get {
                return ((string)(this["getInfo_remoteUserName"]));
            }
            set {
                this["getInfo_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getInfo_queryWord {
            get {
                return ((string)(this["getInfo_queryWord"]));
            }
            set {
                this["getInfo_queryWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getInfo_formatList {
            get {
                return ((string)(this["getInfo_formatList"]));
            }
            set {
                this["getInfo_formatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_dbNameList {
            get {
                return ((string)(this["search_dbNameList"]));
            }
            set {
                this["search_dbNameList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_queryWord {
            get {
                return ((string)(this["search_queryWord"]));
            }
            set {
                this["search_queryWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_use {
            get {
                return ((string)(this["search_use"]));
            }
            set {
                this["search_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_matchStyle {
            get {
                return ((string)(this["search_matchStyle"]));
            }
            set {
                this["search_matchStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_formatList {
            get {
                return ((string)(this["search_formatList"]));
            }
            set {
                this["search_formatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_remoteUserName {
            get {
                return ((string)(this["search_remoteUserName"]));
            }
            set {
                this["search_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("getPatronInfo")]
        public string getInfo_method {
            get {
                return ((string)(this["getInfo_method"]));
            }
            set {
                this["getInfo_method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("searchPatron")]
        public string search_method {
            get {
                return ((string)(this["search_method"]));
            }
            set {
                this["search_method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string search_resultSetName {
            get {
                return ((string)(this["search_resultSetName"]));
            }
            set {
                this["search_resultSetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,100")]
        public string search_position {
            get {
                return ((string)(this["search_position"]));
            }
            set {
                this["search_position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bindPatron_remoteUserName {
            get {
                return ((string)(this["bindPatron_remoteUserName"]));
            }
            set {
                this["bindPatron_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bind")]
        public string bindPatron_action {
            get {
                return ((string)(this["bindPatron_action"]));
            }
            set {
                this["bindPatron_action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bindPatron_queryWord {
            get {
                return ((string)(this["bindPatron_queryWord"]));
            }
            set {
                this["bindPatron_queryWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bindPatron_password {
            get {
                return ((string)(this["bindPatron_password"]));
            }
            set {
                this["bindPatron_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bindPatron_bindingID {
            get {
                return ((string)(this["bindPatron_bindingID"]));
            }
            set {
                this["bindPatron_bindingID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("single")]
        public string bindPatron_style {
            get {
                return ((string)(this["bindPatron_style"]));
            }
            set {
                this["bindPatron_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml")]
        public string bindPatron_resultTypeList {
            get {
                return ((string)(this["bindPatron_resultTypeList"]));
            }
            set {
                this["bindPatron_resultTypeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setInfo_method {
            get {
                return ((string)(this["setInfo_method"]));
            }
            set {
                this["setInfo_method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setInfo_remoteUserName {
            get {
                return ((string)(this["setInfo_remoteUserName"]));
            }
            set {
                this["setInfo_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setInfo_biblioRecPath {
            get {
                return ((string)(this["setInfo_biblioRecPath"]));
            }
            set {
                this["setInfo_biblioRecPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setInfo_action {
            get {
                return ((string)(this["setInfo_action"]));
            }
            set {
                this["setInfo_action"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_remoteUserName {
            get {
                return ((string)(this["circulation_remoteUserName"]));
            }
            set {
                this["circulation_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_operation {
            get {
                return ((string)(this["circulation_operation"]));
            }
            set {
                this["circulation_operation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_patron {
            get {
                return ((string)(this["circulation_patron"]));
            }
            set {
                this["circulation_patron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_item {
            get {
                return ((string)(this["circulation_item"]));
            }
            set {
                this["circulation_item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_style {
            get {
                return ((string)(this["circulation_style"]));
            }
            set {
                this["circulation_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_patronFormatList {
            get {
                return ((string)(this["circulation_patronFormatList"]));
            }
            set {
                this["circulation_patronFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_itemFormatList {
            get {
                return ((string)(this["circulation_itemFormatList"]));
            }
            set {
                this["circulation_itemFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string circulation_biblioFormatList {
            get {
                return ((string)(this["circulation_biblioFormatList"]));
            }
            set {
                this["circulation_biblioFormatList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string message_groupName {
            get {
                return ((string)(this["message_groupName"]));
            }
            set {
                this["message_groupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string message_timeRange {
            get {
                return ((string)(this["message_timeRange"]));
            }
            set {
                this["message_timeRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_remoteUserName {
            get {
                return ((string)(this["getRes_remoteUserName"]));
            }
            set {
                this["getRes_remoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_operation {
            get {
                return ((string)(this["getRes_operation"]));
            }
            set {
                this["getRes_operation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_path {
            get {
                return ((string)(this["getRes_path"]));
            }
            set {
                this["getRes_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_start {
            get {
                return ((string)(this["getRes_start"]));
            }
            set {
                this["getRes_start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_length {
            get {
                return ((string)(this["getRes_length"]));
            }
            set {
                this["getRes_length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_style {
            get {
                return ((string)(this["getRes_style"]));
            }
            set {
                this["getRes_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string getRes_outputFile {
            get {
                return ((string)(this["getRes_outputFile"]));
            }
            set {
                this["getRes_outputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string message_userRange {
            get {
                return ((string)(this["message_userRange"]));
            }
            set {
                this["message_userRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string message_sortCondition {
            get {
                return ((string)(this["message_sortCondition"]));
            }
            set {
                this["message_sortCondition"] = value;
            }
        }
    }
}
